package com.example.trace.util;

import com.example.trace.common.BizException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.test.util.ReflectionTestUtils;

import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.util.Base64;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class SignatureUtilTest {

    @TempDir
    Path tempDir;

    @Test
    void init_shouldGenerateTemporaryInMemoryKeyPairWhenAutoGenerateEnabled() {
        SignatureUtil util = new SignatureUtil();
        ReflectionTestUtils.setField(util, "autoGenerate", true);
        ReflectionTestUtils.setField(util, "keyId", "test-key");
        ReflectionTestUtils.setField(util, "keyVersion", 7);
        ReflectionTestUtils.setField(util, "privateKeyPath", "   ");
        ReflectionTestUtils.setField(util, "publicKeyPath", "");

        util.init();

        String signature = util.sign("trace-payload");
        assertThat(util.verify("trace-payload", signature)).isTrue();
        assertThat(SignatureUtil.verifyWithPublicKey("trace-payload", signature, util.getPublicKeyBase64())).isTrue();
        assertThat(util.verify("trace-payload", signature, "test-key", 7)).isTrue();
        assertThat(util.verify("trace-payload", signature, "other-key", 7)).isFalse();
        assertThat(util.getKeyId()).isEqualTo("test-key");
        assertThat(util.getKeyVersion()).isEqualTo(7);
        assertThat(Files.exists(tempDir.resolve("private_key.pem"))).isFalse();
    }

    @Test
    void init_shouldLoadFixedKeyPairFromExternalFiles() throws Exception {
        KeyPair keyPair = generateKeyPair();
        Path privateKeyPath = tempDir.resolve("private_key.pem");
        Path publicKeyPath = tempDir.resolve("public_key.pem");
        Files.writeString(privateKeyPath, toPem("PRIVATE KEY", keyPair.getPrivate().getEncoded()), StandardCharsets.UTF_8);
        Files.writeString(publicKeyPath, toPem("PUBLIC KEY", keyPair.getPublic().getEncoded()), StandardCharsets.UTF_8);

        SignatureUtil util = new SignatureUtil();
        ReflectionTestUtils.setField(util, "autoGenerate", false);
        ReflectionTestUtils.setField(util, "keyId", "file-key");
        ReflectionTestUtils.setField(util, "keyVersion", 3);
        ReflectionTestUtils.setField(util, "privateKeyPath", privateKeyPath.toString());
        ReflectionTestUtils.setField(util, "publicKeyPath", publicKeyPath.toString());

        util.init();

        String signature = util.sign("trace-payload");
        assertThat(util.verify("trace-payload", signature)).isTrue();
        assertThat(util.verify("trace-payload", signature, "file-key", 3)).isTrue();
        assertThat(util.verify("trace-payload", signature, "file-key", 4)).isFalse();
        assertThat(SignatureUtil.verifyWithPublicKey("trace-payload", signature, util.getPublicKeyBase64())).isTrue();
    }

    @Test
    void init_shouldFailWhenKeysAreMissingAndAutoGenerateDisabled() {
        SignatureUtil util = new SignatureUtil();
        ReflectionTestUtils.setField(util, "autoGenerate", false);
        ReflectionTestUtils.setField(util, "privateKeyPath", "");
        ReflectionTestUtils.setField(util, "publicKeyPath", "");

        assertThatThrownBy(util::init)
                .isInstanceOf(BizException.class)
                .hasCauseInstanceOf(IllegalStateException.class)
                .hasRootCauseMessage("Signature keys are not configured and auto-generation is disabled");
    }

    @Test
    void init_shouldFailWhenOnlyOneKeyPathIsConfigured() {
        SignatureUtil util = new SignatureUtil();
        ReflectionTestUtils.setField(util, "autoGenerate", false);
        ReflectionTestUtils.setField(util, "privateKeyPath", tempDir.resolve("private_key.pem").toString());
        ReflectionTestUtils.setField(util, "publicKeyPath", "");

        assertThatThrownBy(util::init)
                .isInstanceOf(BizException.class)
                .hasCauseInstanceOf(IllegalStateException.class)
                .hasRootCauseMessage("Both TRACE_SIGNATURE_PRIVATE_KEY_PATH and TRACE_SIGNATURE_PUBLIC_KEY_PATH must be configured together");
    }

    @Test
    void buildSignatureData_shouldIncludeOperatorOnlyInCurrentPayload() {
        String currentPayload = SignatureUtil.buildSignatureData(
                "trace-1",
                "INBOUND",
                "factory-A",
                "warehouse-B",
                "浙江省",
                "杭州市",
                "2026-05-05T18:40",
                "2026-05-05T18:40",
                "GENESIS",
                "hash-1",
                null,
                "scanner",
                "sealed"
        );
        String legacyPayload = SignatureUtil.buildLegacySignatureData(
                "trace-1",
                "INBOUND",
                "factory-A",
                "warehouse-B",
                "浙江省",
                "杭州市",
                "2026-05-05T18:40",
                "2026-05-05T18:40",
                "GENESIS",
                "hash-1",
                null,
                "sealed"
        );

        assertThat(currentPayload).contains("operator=scanner");
        assertThat(currentPayload).contains("remark=sealed");
        assertThat(legacyPayload).doesNotContain("operator=");
        assertThat(legacyPayload).contains("remark=sealed");
    }

    private static KeyPair generateKeyPair() throws Exception {
        KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
        generator.initialize(2048);
        return generator.generateKeyPair();
    }

    private static String toPem(String type, byte[] encoded) {
        String body = Base64.getMimeEncoder(64, System.lineSeparator().getBytes(StandardCharsets.UTF_8))
                .encodeToString(encoded);
        return "-----BEGIN " + type + "-----" + System.lineSeparator()
                + body + System.lineSeparator()
                + "-----END " + type + "-----" + System.lineSeparator();
    }
}
