package com.example.trace.config;

import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationContextInitializer;
import org.springframework.core.io.support.SpringFactoriesLoader;
import org.springframework.mock.env.MockEnvironment;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class ProdProfileConfigGuardTest {

    private static final String VALID_PROD_SECRET = "ProdJwtSecretKeyWithAtLeast32Bytes2026!";

    @Test
    void springFactories_shouldRegisterProdConfigGuardInitializer() {
        assertThat(SpringFactoriesLoader.loadFactories(
                ApplicationContextInitializer.class,
                getClass().getClassLoader()
        )).anyMatch(ProdProfileConfigGuard.class::isInstance);
    }

    @Test
    void validate_shouldRejectMissingJwtSecretInProd() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt();

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("TRACE_JWT_SECRET");
    }

    @Test
    void validate_shouldRejectDefaultJwtSecretInProd() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", ProdProfileConfigGuard.DEV_DEFAULT_JWT_SECRET);

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("default or placeholder JWT secret");
    }

    @Test
    void validate_shouldRejectRootRootDatasourceCredentialsInProd() {
        MockEnvironment environment = new MockEnvironment();
        environment.setActiveProfiles("prod");
        environment
                .withProperty("jwt.secret", VALID_PROD_SECRET)
                .withProperty("spring.datasource.url", "jdbc:mysql://db.example.internal:3306/trace_db")
                .withProperty("spring.datasource.username", "root")
                .withProperty("spring.datasource.password", "root");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("root/root");
    }

    @Test
    void validate_shouldRejectMissingSignatureKeyPathsInProd() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", VALID_PROD_SECRET);

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("TRACE_SIGNATURE_PRIVATE_KEY_PATH");
    }

    @Test
    void validate_shouldRejectAutoGeneratedSignatureKeysInProd() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", VALID_PROD_SECRET)
                .withProperty("trace.signature.private-key-path", "/etc/trace/signing/private_key.pem")
                .withProperty("trace.signature.public-key-path", "/etc/trace/signing/public_key.pem")
                .withProperty("trace.signature.key-id", "default")
                .withProperty("trace.signature.key-version", "1")
                .withProperty("trace.signature.auto-generate", "true");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("TRACE_SIGNATURE_AUTO_GENERATE");
    }

    @Test
    void validate_shouldRejectWorkspaceDefaultSignatureKeyPathInProd() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", VALID_PROD_SECRET)
                .withProperty("trace.signature.private-key-path", "d:/bysj/backend/keys/private_key.pem")
                .withProperty("trace.signature.public-key-path", "d:/bysj/backend/keys/public_key.pem")
                .withProperty("trace.signature.key-id", "default")
                .withProperty("trace.signature.key-version", "1");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("externally mounted files");
    }

    @Test
    void validate_shouldRejectMissingSignatureKeyMetadataInProd() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", VALID_PROD_SECRET)
                .withProperty("trace.signature.private-key-path", "/etc/trace/signing/private_key.pem")
                .withProperty("trace.signature.public-key-path", "/etc/trace/signing/public_key.pem")
                .withProperty("trace.signature.auto-generate", "false");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("TRACE_SIGNATURE_KEY_ID");
    }

    @Test
    void validate_shouldPassWhenProdConfigIsExplicitAndStrong() {
        MockEnvironment environment = validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", VALID_PROD_SECRET)
                .withProperty("trace.signature.private-key-path", "/etc/trace/signing/private_key.pem")
                .withProperty("trace.signature.public-key-path", "/etc/trace/signing/public_key.pem")
                .withProperty("trace.signature.key-id", "default")
                .withProperty("trace.signature.key-version", "1")
                .withProperty("trace.signature.auto-generate", "false")
                .withProperty("cors.allowed-origins", "https://trace.example.com");

        assertThatCode(() -> ProdProfileConfigGuard.validate(environment))
                .doesNotThrowAnyException();
    }

    @Test
    void validate_shouldRejectMissingCorsConfigurationInProd() {
        MockEnvironment environment = validProdSignatureEnvironment();
        // 留空 cors.allowed-origins 与 cors.allowed-origin-patterns，模拟部署人忘记设置环境变量。

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("TRACE_CORS_ALLOWED_ORIGINS")
                .hasMessageContaining("TRACE_CORS_ALLOWED_ORIGIN_PATTERNS");
    }

    @Test
    void validate_shouldAllowProdWithOnlyAllowedOriginsConfigured() {
        MockEnvironment environment = validProdSignatureEnvironment()
                .withProperty("cors.allowed-origins", "https://trace.example.com,https://admin.trace.example.com");

        assertThatCode(() -> ProdProfileConfigGuard.validate(environment))
                .doesNotThrowAnyException();
    }

    @Test
    void validate_shouldAllowProdWithOnlyAllowedOriginPatternsConfigured() {
        MockEnvironment environment = validProdSignatureEnvironment()
                .withProperty("cors.allowed-origin-patterns", "https://192.168.10.*:5173");

        assertThatCode(() -> ProdProfileConfigGuard.validate(environment))
                .doesNotThrowAnyException();
    }

    @Test
    void validate_shouldRejectWildcardOnlyCorsOriginsInProd() {
        MockEnvironment environment = validProdSignatureEnvironment()
                .withProperty("cors.allowed-origins", "*");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("wildcard '*'");
    }

    @Test
    void validate_shouldRejectWildcardOnlyCorsPatternsInProd() {
        MockEnvironment environment = validProdSignatureEnvironment()
                .withProperty("cors.allowed-origin-patterns", "*");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("wildcard '*'");
    }

    @Test
    void validate_shouldRejectPlaceholderCorsConfigurationInProd() {
        MockEnvironment environment = validProdSignatureEnvironment()
                .withProperty("cors.allowed-origins", "<replace-with-frontend-domain>");

        assertThatThrownBy(() -> ProdProfileConfigGuard.validate(environment))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("TRACE_CORS_ALLOWED_ORIGINS");
    }

    @Test
    void validate_shouldAllowMixedWildcardAndExplicitOrigins() {
        // 仅 "*" 单独全开会被拒绝；但若同时含 "*" 和具体域名，containsWildcardOnly 返回 false，
        // 校验通过——这是为了让"开放给所有 + 同时显式列出可信域名"的边缘配置不被误伤。
        // 真正的"完全开放"风险靠 "*" 单独项识别。
        MockEnvironment environment = validProdSignatureEnvironment()
                .withProperty("cors.allowed-origins", "*,https://trace.example.com");

        assertThatCode(() -> ProdProfileConfigGuard.validate(environment))
                .doesNotThrowAnyException();
    }

    @Test
    void validate_shouldIgnoreDevelopmentProfileDefaults() {
        MockEnvironment environment = new MockEnvironment();
        environment.setActiveProfiles("dev");
        environment
                .withProperty("jwt.secret", ProdProfileConfigGuard.DEV_DEFAULT_JWT_SECRET)
                .withProperty("spring.datasource.url", "jdbc:mysql://localhost:3306/trace_db")
                .withProperty("spring.datasource.username", "root")
                .withProperty("spring.datasource.password", "root");

        assertThatCode(() -> ProdProfileConfigGuard.validate(environment))
                .doesNotThrowAnyException();
    }

    private static MockEnvironment validProdEnvironmentWithoutJwt() {
        MockEnvironment environment = new MockEnvironment();
        environment.setActiveProfiles("prod");
        environment
                .withProperty("spring.datasource.url", "jdbc:mysql://db.example.internal:3306/trace_db")
                .withProperty("spring.datasource.username", "trace_app")
                .withProperty("spring.datasource.password", "nonDefaultDbPassword2026!");
        return environment;
    }

    /**
     * 构造一个 JWT/DB/签名密钥都齐全合法的 prod 环境，但 <b>不设置 CORS</b>。
     * 用于专测 CORS 校验路径——保证执行流能走到 {@code validateCors} 而不会更早失败。
     */
    private static MockEnvironment validProdSignatureEnvironment() {
        return validProdEnvironmentWithoutJwt()
                .withProperty("jwt.secret", VALID_PROD_SECRET)
                .withProperty("trace.signature.private-key-path", "/etc/trace/signing/private_key.pem")
                .withProperty("trace.signature.public-key-path", "/etc/trace/signing/public_key.pem")
                .withProperty("trace.signature.key-id", "default")
                .withProperty("trace.signature.key-version", "1")
                .withProperty("trace.signature.auto-generate", "false");
    }
}